language: bash

services:
  - docker

env:
  - GEOSERVER_VERSION=2.13.1

script:
  - make

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push meteofi/geoservertest
